function plot_overflow(system)
% 
%  Plot the overflow output of your system.
%
%  Function: plot_overflow(system)
%
%  where: 
%  system is a struct from a counterexample extracted (generated by .MAT file). 
%     
% Federal University of Amazonas
% May 15, 2017
% Manaus, Brazil

a = system.sys.a;
b = system.sys.b;

delta = system.impl.delta;

l = system.impl.frac_bits;
n = system.impl.int_bits - 1;

if (delta > 0)
[a_num, b_num] = deltapoly(b, a, delta);
else
a_num = a;
b_num = b;
end

a_fxp = fxp_rounding(a_num,l);
b_fxp = fxp_rounding(b_num,l);

uf =  system.inputs.const_inputs;

y = dlsim(b_fxp,a_fxp,uf);

min = -1*((2^n));
max = ((2^n)-2^(-1*l));

stairs(y);
hold on;
plot([1:length(y)],min*ones(length(y),1),'r')
plot([1:length(y)],max*ones(length(y),1),'r')
hold off

title('Overflow Dectection');
ylabel ('Outputs (y)');
xlabel ('Number of Occurencies');
legend('Signal Y','Limits of Word Length')
grid on;

end
