function plot_zero_pole(system)
%
%  Plot the poles and zeros of your system (very useful to check stability and minimum phase)
%  considering fwl effects.
%
%  Function: plot_limit_cycle(system)
%
%  where:
%  system is a struct from a counterexample extracted (generated by .MAT file).
%
% Federal University of Amazonas
% May 15, 2017
% Manaus, Brazil

num = system.sys.b;
den = system.sys.a;

num_fxp = fwl(num,system.impl.frac_bits);
den_fxp = fwl(den,system.impl.frac_bits);

figure
subplot(211)
zplane(num,den)
legend('zeros','poles','unitary circle')
title('Unitary circle of Z-plane Without FWL Effects');

subplot(212)
zplane(num_fxp,den_fxp)
legend('zeros','poles','unitary circle')
title('Unitary circle of Z-plane With FWL Effects');

end
