function synthExtract(path, type)
% Get the result form the controller synthesized and then extract the controller coefficients
%
% Function: synthExtract(path, type)
% 
% path: path with the log file generated by synthesis
% type: 'ss' for state-space or 'tf' for transfer-function;
%
% Author: Lennon Chaves
% 
% March 2017
%
user = userpath;

if strfind(user,'/Documents/MATLAB') %default folder installation
    install_folder = [user '/Add-Ons/Toolboxes/DSSynth/code'];
else
    install_folder = [user '/Toolboxes/DSSynth/code'];
end

if (strcmp(type, 'tf'))
 logfile = 'system_bound_simple.log';
 runner = [install_folder '/dssynth-tf-extract.sh'];
 command = ['sh ' runner ' ' logfile];
elseif (strcmp(type, 'ss'))
 logfile = 'system_completeness-threshold-ss.log';
 runner = [install_folder '/dssynth-ss-extract.sh'];
 command = ['sh ' runner ' ' logfile];
end 

system(command);

end
