function plot_limit_cycle(system)
% 
%  Plot the limit cycle output of your system.
%
%  Function: plot_limit_cycle(system)
%
%  where:
%  system is a struct from a counterexample extracted (generated by .MAT file). 
%     
% Lennon Chaves
% October 09, 2016
% Manaus

y = [system.output.output_verification system.output.output_verification];
stairs(y,'r');

title('Limit Cycle');
ylabel ('Amplitude');
xlabel ('Outputs (y)');
grid on;

end
