function plot_overflow(system)
% 
%  Plot the overflow output of your system.
%
%  plot_overflow(system)
%  Where system is a struct from a counterexample extracted (generated by .MAT file). 
%     
% Lennon Chaves
% October 08, 2016
% Manaus

a = system.sys.a;
b = system.sys.b;

u = system.inputs.const_inputs;
delta = system.impl.delta;
l = system.impl.frac_bits;
n = l + system.impl.int_bits - 1;

if delta > 0
    [at,bt]=deltapoly(b,a,delta);
else
    at=a;
    bt=b;
end

uf=(2^(l))*u;

y=dlsim(bt,at,uf);

stairs(y);
hold on;
plot([1:length(y)],-1*(((2^n)-1))*ones(length(y),1),'r')
plot([1:length(y)],(((2^n)-1))*ones(length(y),1),'r')
hold off

title('Overflow Dectection');
ylabel ('Amplitude');
xlabel ('Outputs (y)');
legend('Signal Y','Limits of Word Length')
grid on;

end
