function plot_overflow(system)
% 
%  Plot the overflow output of your system.
%
%  Function: plot_overflow(system)
%
%  where: 
%  system is a struct from a counterexample extracted (generated by .MAT file). 
%     
% Lennon Chaves
% October 09, 2016
% Manaus, Brazil

a = system.sys.a;
b = system.sys.b;

u = system.inputs.const_inputs;
delta = system.impl.delta;
l = system.impl.frac_bits;
n = system.impl.int_bits - 1;

if delta > 0
    [at,bt]=deltapoly(b,a,delta);
else
    at=a;
    bt=b;
end

for i=1:length(at)
at(i) = mode_saturate(at(i),n+1,l);
end
for i=1:length(bt)
bt(i) = mode_saturate(bt(i),n+1,l);
end

uf=u;

y=dlsim(bt,at,uf);
min = -1*((2^n));
max = ((2^n)-2^(-1*l));

stairs(y);
hold on;
plot([1:length(y)],min*ones(length(y),1),'r')
plot([1:length(y)],max*ones(length(y),1),'r')
hold off

title('Overflow Dectection');
ylabel ('Outputs (y)');
xlabel ('Number of Occurencies');
legend('Signal Y','Limits of Word Length')
grid on;

end
